import { adminAuth, adminDb } from "@/lib/firebase/firebaseAdmin";
import { prisma } from "@/lib/prisma";

function date(value: unknown) {
  if (!value) return undefined;
  if (typeof (value as { toDate?: () => Date }).toDate === "function") return (value as { toDate: () => Date }).toDate();
  const d = new Date(value as string | number | Date);
  return Number.isNaN(d.getTime()) ? undefined : d;
}
function text(value: unknown) { return typeof value === "string" ? value : value == null ? "" : String(value); }
function bool(value: unknown) { return value === true; }
function enumOr<T extends string>(value: unknown, values: readonly T[], fallback: T) { return values.includes(value as T) ? value as T : fallback; }

async function migrateProducts() {
  const snap = await adminDb.collection("products").get();
  for (const doc of snap.docs) {
    const d = doc.data(); const createdAt = date(d.createdAt) || new Date();
    await prisma.product.upsert({ where: { id: doc.id }, update: { name:text(d.name), code:text(d.code), category:text(d.category), shortDescription:text(d.shortDescription), fullDescription:text(d.fullDescription), material:text(d.material), lensIndex:text(d.lensIndex), coating:text(d.coating), technology:text(d.technology), imageUrl:text(d.imageUrl), coverImageUrl:text(d.coverImageUrl), videoUrl:text(d.videoUrl), pdfUrl:text(d.pdfUrl), status:enumOr(d.status,["active","draft"] as const,"draft"), featured:bool(d.featured), seoTitle:text(d.seoTitle), seoDescription:text(d.seoDescription) }, create: { id:doc.id, name:text(d.name), code:text(d.code), category:text(d.category), shortDescription:text(d.shortDescription), fullDescription:text(d.fullDescription), material:text(d.material), lensIndex:text(d.lensIndex), coating:text(d.coating), technology:text(d.technology), imageUrl:text(d.imageUrl), coverImageUrl:text(d.coverImageUrl), videoUrl:text(d.videoUrl), pdfUrl:text(d.pdfUrl), status:enumOr(d.status,["active","draft"] as const,"draft"), featured:bool(d.featured), seoTitle:text(d.seoTitle), seoDescription:text(d.seoDescription), createdAt } });
  }
  console.log(`Products: ${snap.size}`);
}

async function migrateCategories() { const snap=await adminDb.collection("categories").get(); for(const doc of snap.docs){const d=doc.data();await prisma.category.upsert({where:{id:doc.id},update:{name:text(d.name),slug:text(d.slug)||doc.id,description:text(d.description),status:enumOr(d.status,["active","draft"] as const,"active")},create:{id:doc.id,name:text(d.name),slug:text(d.slug)||doc.id,description:text(d.description),status:enumOr(d.status,["active","draft"] as const,"active"),createdAt:date(d.createdAt)||new Date()}})} console.log(`Categories: ${snap.size}`); }
async function migrateDealers() { const snap=await adminDb.collection("dealers").get(); const fields=["dealerName","shopName","ownerName","mobile","whatsapp","email","gstNumber","address","city","state","pincode","dealerType","existingBrands","monthlyPurchase","interestedProducts","salesRepresentative","notes"] as const; for(const doc of snap.docs){const d=doc.data();const data:any={id:doc.id,status:enumOr(d.status,["new","contacted","active","rejected"] as const,"new"),createdAt:date(d.createdAt)||new Date()};for(const f of fields)data[f]=text(d[f]);await prisma.dealer.upsert({where:{id:doc.id},update:{...data,createdAt:undefined},create:data})} console.log(`Dealers: ${snap.size}`); }
async function migrateDownloads() { const snap=await adminDb.collection("downloads").get(); for(const doc of snap.docs){const d=doc.data();await prisma.download.upsert({where:{id:doc.id},update:{title:text(d.title),type:text(d.type),category:text(d.category),fileUrl:text(d.fileUrl),status:enumOr(d.status,["active","draft"] as const,"active"),featured:bool(d.featured)},create:{id:doc.id,title:text(d.title),type:text(d.type),category:text(d.category),fileUrl:text(d.fileUrl),status:enumOr(d.status,["active","draft"] as const,"active"),featured:bool(d.featured),createdAt:date(d.createdAt)||new Date()}})} console.log(`Downloads: ${snap.size}`); }
async function migrateGallery() { const snap=await adminDb.collection("gallery").get(); for(const doc of snap.docs){const d=doc.data();await prisma.galleryItem.upsert({where:{id:doc.id},update:{title:text(d.title),category:text(d.category),description:text(d.description),imageUrl:text(d.imageUrl),mediaType:enumOr(d.mediaType,["image","video"] as const,"image"),displayOrder:Number(d.displayOrder)||0,status:enumOr(d.status,["active","draft"] as const,"active"),featured:bool(d.featured)},create:{id:doc.id,title:text(d.title),category:text(d.category),description:text(d.description),imageUrl:text(d.imageUrl),mediaType:enumOr(d.mediaType,["image","video"] as const,"image"),displayOrder:Number(d.displayOrder)||0,status:enumOr(d.status,["active","draft"] as const,"active"),featured:bool(d.featured),createdAt:date(d.createdAt)||new Date()}})} console.log(`Gallery: ${snap.size}`); }
async function migrateBlogs() { const snap=await adminDb.collection("blogs").get(); for(const doc of snap.docs){const d=doc.data();await prisma.blogPost.upsert({where:{id:doc.id},update:{title:text(d.title),slug:text(d.slug)||doc.id,shortDescription:text(d.shortDescription),content:text(d.content),imageUrl:text(d.imageUrl),author:text(d.author),category:text(d.category),status:enumOr(d.status,["active","draft"] as const,"draft"),featured:bool(d.featured),seoTitle:text(d.seoTitle),seoDescription:text(d.seoDescription)},create:{id:doc.id,title:text(d.title),slug:text(d.slug)||doc.id,shortDescription:text(d.shortDescription),content:text(d.content),imageUrl:text(d.imageUrl),author:text(d.author),category:text(d.category),status:enumOr(d.status,["active","draft"] as const,"draft"),featured:bool(d.featured),seoTitle:text(d.seoTitle),seoDescription:text(d.seoDescription),createdAt:date(d.createdAt)||new Date()}})} console.log(`Blogs: ${snap.size}`); }
async function migrateSettings() { const doc=await adminDb.collection("settings").doc("website").get(); if(!doc.exists)return; const d=doc.data()||{}; const fields=["heroTitle","heroHighlight","heroSubtitle","primaryButtonText","primaryButtonUrl","secondaryButtonText","secondaryButtonUrl","galleryHeroTitle","galleryHeroHighlight","galleryHeroSubtitle","companyPhone","companyEmail","companyAddress","instagramUrl","facebookUrl","whatsappUrl","seoTitle","seoDescription"] as const; const data:any={id:"website"};for(const f of fields)data[f]=text(d[f]);await prisma.websiteSettings.upsert({where:{id:"website"},update:data,create:data});console.log("Settings: 1"); }
async function migrateAdmins() { const snap=await adminDb.collection("admins").get(); for(const doc of snap.docs){const d=doc.data();await prisma.admin.upsert({where:{uid:doc.id},update:{name:text(d.name),email:text(d.email).toLowerCase(),role:enumOr(d.role,["owner","super_admin","admin","editor"] as const,"admin"),status:enumOr(d.status,["active","disabled"] as const,"active")},create:{uid:doc.id,name:text(d.name),email:text(d.email).toLowerCase(),role:enumOr(d.role,["owner","super_admin","admin","editor"] as const,"admin"),status:enumOr(d.status,["active","disabled"] as const,"active"),createdBy:text(d.createdBy)||null,createdAt:date(d.createdAt)||new Date()}})} console.log(`Admins: ${snap.size}`); }
async function migrateActivity() { const snap=await adminDb.collection("activityLogs").orderBy("createdAt","asc").get(); for(const doc of snap.docs){const d=doc.data();await prisma.activityLog.upsert({where:{id:doc.id},update:{action:text(d.action),message:text(d.message),performedBy:text(d.performedBy),performedByEmail:text(d.performedByEmail),targetUid:text(d.targetUid)||null,targetEmail:text(d.targetEmail)||null},create:{id:doc.id,action:text(d.action),message:text(d.message),performedBy:text(d.performedBy),performedByEmail:text(d.performedByEmail),targetUid:text(d.targetUid)||null,targetEmail:text(d.targetEmail)||null,createdAt:date(d.createdAt)||new Date()}})} console.log(`Activity logs: ${snap.size}`); }

async function main(){console.log("Migrating Firestore → Neon PostgreSQL...");await migrateProducts();await migrateCategories();await migrateDealers();await migrateDownloads();await migrateGallery();await migrateBlogs();await migrateSettings();await migrateAdmins();await migrateActivity();console.log("Migration complete.");}
main().catch((error)=>{console.error(error);process.exitCode=1}).finally(async()=>{await prisma.$disconnect()});
